services:
  app:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
  # service with backend
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment: 
      - MONGO_URL=mongodb://the_username:the_password@192.168.104.101:3456
    container_name: backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    container_name: reverse-proxy
    depends_on:
      - app
      - backend